from langgraph.graph import StateGraph, END
from typing import TypedDict
from extractor_agent import extractor_agent, readPDFS
from timeline_agent import timeline_agent
from conflict_agent import conflict_agent
from reporter_agent import reporter_agent
from outreach_agent import outreach_agent
from rag import store_reports

# orchestrator: connect all 5 agents together in the right order using langgraph
# langgraph manages a shared state (like a notebook) that every agent reads from and writes to
# each agent adds its output to the state and passes it to the next agent
# without this file the agents are isolated and dony know about each others 

# shared state: a dictionary that gets passed between all agents
# every agent reads what it needs from here and saves its output back here
class HealthState(TypedDict):
    folder_path: str        # path to the folder containing all medical pdfs
    raw_texts: dict         # raw text extracted from each pdf (filename: text)
    outreach_result: str    # email drafts generated by agent 0
    extracted_data: list    # structured dicts extracted by agent 1 (one dict per report)
    timeline: str           # chronological health narrative built by agent 2
    conflicts: str          # contradictions and gaps found by agent 3
    final_report: str       # patient friendly summary written by agent 4
    figure: object          # blood pressure graph generated by agent 4


# each function below is one node in the langgraph
# a node = one agent running its job then saving result back to state (so if the next agent need the previous agent output he can take it)


def run_outreach(state):# agent 0: read all pdfs from folder then generate email drafts for missing records
    raw_texts = readPDFS(state["folder_path"])
    result = outreach_agent("\n".join(raw_texts.values()))
    return {**state, "raw_texts": raw_texts, "outreach_result": result}

def run_extractor(state): # agent 1: extract structured data from each pdf and store all texts in chromadb for rag
    data = extractor_agent(state["folder_path"])
    store_reports(state["raw_texts"])  # store raw texts in chromadb so user can ask questions later
    return {**state, "extracted_data": data}

def run_timeline(state):# agent 2: sort extracted data by date and build chronological health narrative
    return {**state, "timeline": timeline_agent(state["extracted_data"])}

def run_conflict(state):# agent 3: compare all reports and find contradictions and gaps
    return {**state, "conflicts": conflict_agent(state["timeline"], state["extracted_data"])}

def run_reporter(state):# agent 4: write final patient friendly report and generate blood pressure graph
    report, fig = reporter_agent(state["timeline"], state["conflicts"], state["extracted_data"])
    return {**state, "final_report": report, "figure": fig}


# build the langgraph workflow
# add each agent as a node then connect them with edges in the right order
workflow = StateGraph(HealthState)

# add nodes (each node = one agent)
workflow.add_node("outreach", run_outreach)
workflow.add_node("extractor", run_extractor)
workflow.add_node("timeline", run_timeline)
workflow.add_node("conflict", run_conflict)
workflow.add_node("reporter", run_reporter)

# connect agents in order with edges
# edge means: when this agent finishes run the next one
workflow.set_entry_point("outreach")         # start with agent 0
workflow.add_edge("outreach", "extractor")   # agent 0 done run agent 1
workflow.add_edge("extractor", "timeline")   # agent 1 done run agent 2
workflow.add_edge("timeline", "conflict")    # agent 2 done run agent 3
workflow.add_edge("conflict", "reporter")    # agent 3 done run agent 4
workflow.add_edge("reporter", END)           # agent 4 done end the pipeline

# compile build the final runnable pipeline from the graph we defined
app = workflow.compile()


def run_pipeline(folder_path: str) -> dict:
    # this is the only function the streamlit app needs to call
    # it takes the folder path runs all 5 agents in order
    # and returns the final state with everything in it
    return app.invoke({
        "folder_path": folder_path,
        "raw_texts": {},
        "outreach_result": "",
        "extracted_data": [],
        "timeline": "",
        "conflicts": "",
        "final_report": "",
        "figure": None})

# test
if __name__ == "__main__":
    result = run_pipeline(r"C:\Users\Lenovo\AI-Agents-Internship\day15(capstone)\sample_reports(to")
    print(result["final_report"])